### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by mjsalinger** [Clever/saml2#103]
There are a few PRs here that would be worth having merged and released, but haven't seen any other activity since Jan.  Is this repo still active?

**Comment by mohit** [comment]
Hi @mjsalinger, the repo is still active and we're using it. Unfortunately we have missed on the response to PRs and Issues on Github (we use a different tracker internally).

Thanks for the note - will follow up on issues and PRs over the next couple of weeks.

**Comment by mjsalinger** [comment]
Thanks!
