### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by mikevbaker** [Clever/saml2#105]
I'm trying to get a look at the library to see if I can use it in a project and I'm getting install errors. 

First I tried line one from the readme:

E:\Dev\Libraries\saml2-master>npm install saml2-js --save
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "saml2-js" "--save"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF
npm ERR! Refusing to install saml2-js as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     E:\Dev\Libraries\saml2-master\npm-debug.log

Then I tried just npm install to have it operate from package.json:

E:\Dev\Libraries\saml2-master>npm install
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> saml2-js@1.11.0 prepublish E:\Dev\Libraries\saml2-master
> make build

'make' is not recognized as an internal or external command,
operable program or batch file.

npm WARN saml2-js@1.11.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! saml2-js@1.11.0 prepublish: `make build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the saml2-js@1.11.0 prepublish script 'make build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the saml2-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs saml2-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls saml2-js
npm ERR! There is likely additional logging output above.

Is there some additional dependency I'm missing? I see a reference to 'make'. What 'make' is this?

TIA
Mike

**Comment by jefff** [comment]
To install this package, you're going to want to run `npm install saml2-js --save` in the directory of your application, which will automatically download a packaged version of this library and allow you to include it. Unless you intend to make changes to this library, there is no need to clone this repo directly.

`make` is a tool for build automation which is not installed by default on Windows. If you wish to make changes to this repo on Windows, you can install it, or read the commands in the `Makefile` and run them directly. But again, this is not needed for the vast majority of people who are just using this library to add SAML support to their application.

I would recommend reading through npm's getting started guide, which should clear up how to manage dependencies for node projects: https://docs.npmjs.com/getting-started/what-is-npm

**Comment by mikevbaker** [comment]
Oh yes, Thanks for the response. I should have realized. I went back to my project (a finished SPA into which I'm trying to add SSO) and ran the command to add saml2-js in and it brought it in just fine.
I remember now why I was going through github rather than just npm install, I was looking for a sample application that I could study. Do you know where I could get a sample nodejs web app using saml2-js?

Thanks
