### ISSUE TITLE
xml-encryption update to fix Jest bug

### ISSUE THREAD

**Issue by jasonblanchard** [Clever/saml2#107]
I was attempting to test some internal code I've built on top of this one in Jest, and importing `saml2-js` anywhere in the dependency tree causes this error when running Jest:

```
    TypeError: mods[i] is not a function

      at Object.module.exports (node_modules/node-forge/js/forge.js:41:14)
      at defineFunc (node_modules/node-forge/js/forge.js:47:10)
      at node_modules/node-forge/js/forge.js:90:14
      at define (node_modules/node-forge/js/forge.js:15:7)
      at define (node_modules/node-forge/js/forge.js:54:22)
      at node_modules/node-forge/js/forge.js:59:1
      at Object.<anonymous> (node_modules/node-forge/js/forge.js:92:3)
```

I've tracked this through [a Jest issue](https://github.com/facebook/jest/issues/1946) to [a fix in node-forge](https://github.com/digitalbazaar/forge/issues/362) which is [a dependency of xml-encryption](https://github.com/auth0/node-xml-encryption/blob/master/package.json#L24), which is [a dependency in this project](https://github.com/Clever/saml2/blob/master/package.json#L35).

Any chance we could get a version bump on that?

Thanks!

**Comment by mohit** [comment]
@jasonblanchard hope https://github.com/Clever/saml2/pull/110 fixes this issue.
