### ISSUE TITLE
fs object returning empty

### ISSUE THREAD

**Issue by guruprasad4643** [Clever/saml2#131]
When we tried to require saml2-js in react component., its throwing an error of fs as empty object.., 
Can anyone help me out ?

**Comment by cozmo** [comment]
This is a nodeJS library, using it on the frontend is not possible due to the neccesity of running in trusted context (like a server).

I’d take a look at the express JS server example in the readme. Closing this issue for now but feel free to re-open/comment if you have additional questions.
