### ISSUE TITLE
WARNING in ./node_modules/saml2-js/index.js 2:17-30 Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by RamJ2EE** [Clever/saml2#132]
I am trying to include saml2-js library in Angular2.5 app and getting the following warning in webpack and error in the browser.

Webpack
=======
![image](https://user-images.githubusercontent.com/34070099/39893357-77f8a9b8-5471-11e8-8a90-bd015e6de4af.png)

Browser
=====
![image](https://user-images.githubusercontent.com/34070099/39893416-9e442b10-5471-11e8-91d1-7b98d8988f10.png)

**Comment by kogden** [comment]
Having this same issue. Causing some serious problems in Angular 6.

**Comment by kogden** [comment]
I think your node files should be moved out of your web project. Node server apps should exist separately.

**Comment by imtiazk** [comment]
Same problem in Vue. Any ideas what is going wrong?

**Comment by mcab** [comment]
Fairly certain this should not be used within client-side applications (via Angular / Vue / etc.). You'd distribute the `private_key` for the service provider, which gives clients the keys of who's authorizing them in the first place.

See https://github.com/Clever/saml2/issues/169#issuecomment-542364962 for more information. Please reopen if this isn't the case.
