### ISSUE TITLE
assert_endpoint: What is it?

### ISSUE THREAD

**Issue by kogden** [Clever/saml2#142]
So the documentation for assert_endpoint isn't very clear. 

`assert_endpoint - Required - URL of service provider assert endpoint.`

As a required parameter this should really be cleared up. In fact, please tell me what it is because I don't know and my application is unfinished until I find out.

**Comment by jefff** [comment]
It's hard to define this without getting tautological, but it's the endpoint at which you should expect to receive and parse an assertion. At this endpoint, you should be calling `sp.post_assert` or `sp.get_assert`. In the example in the README, it's the endpoint defined by `app.post("/assert", function(req, res) {` so it's set to `https://sp.example.com/assert` as if the example code were running at that domain.

**Comment by kogden** [comment]
Thank you! I still think it could be fleshed out in the doc by a sentence or so, but I figured it out.
