### ISSUE TITLE
SAML response is not yet valid

### ISSUE THREAD

**Issue by chetandev** [Clever/saml2#151]
When loggin in using SSO i am  getting following error "SAML response is not yet valid"  most of the times.successful response comes only a few times

**Comment by jgeurts** [comment]
Take a look at `notbefore_skew` option. It defaults to 1s - you may need to increase that to account for any skew between the clock times of the two systems

**Comment by cozmo** [comment]
@jgeurts is correct, closing this issue. 

Please re-open/comment if you continue to have this issue.
