### ISSUE TITLE
What is the purpose of this lib?

### ISSUE THREAD

**Issue by Cidaas** [Clever/saml2#162]
Hi what is the purpose of this library? If I use this library my application became its own idp and sp ? or it just a helper fuction to other provider ?

**Comment by adampopkiewicz** [comment]
for example: As a SP I'm using it to provide integration with my client's IDP.

AFAIK you can do all SAML2 things with this library, depending on your configuration and own, particularly defined purpose. This library helps to wrap around/handle protocol details, including but not limited to things like: handling xml, authentication, validation, encryption/decryption.

it's not a one stop shop but handles SAML2 protocol details and if your service is written in JS it's very convenient.

**Comment by cozmo** [comment]
This library allows your node JS application to be a SAML service provider - That is to say allows you to log users in/authenticate by communicating to a service identity provider (such as active directory). Some more info in #130, and we'll be updating the documentation soon to make this more clear. 

Feel free to comment/re-open if this answer is unsatisfactory.
