### ISSUE TITLE
Purpose of lib

### ISSUE THREAD

**Issue by tzahush** [Clever/saml2#164]
Hello, I am trying to understand if this lib is what i want/need, i was wondering if you can help me underestand..

I currently have a DB full of users, i would like to give them the option to connect to multiple third party SAML operated services, meaning my nodejs server act as a saml IDP.

Then I would need to configure each service.
Is that possible?

**Comment by galkahana** [comment]
#130 

This is for SP implementation only.

**Comment by cozmo** [comment]
@galkahana is correct, although we may add support for the IDP side of things in a coming's update. Regardless we'll certainly clarify in the readme the purpose. 

Closing but please comment/re-open if you have more questions.
