### ISSUE TITLE
Publish 2.0.4 to npm

### ISSUE THREAD

**Issue by gabegorelick** [Clever/saml2#176]
2.0.4 was [committed](https://github.com/Clever/saml2/commit/578363189c1237465b1060fb8b25037e806b860b) months ago but is still not published to npm. The latest version there is still 2.0.3.

**Comment by jnardone** [comment]
@afumagalli @xavi- @bgveenstra are any of you maintainers that can do this at this point?  Who's in charge of this project at this point?

**Comment by gabegorelick** [comment]
Tags also haven't been pushed since v1.0.3: https://github.com/Clever/saml2/releases

**Comment by cozmo** [comment]
We broke the npm auto publish by accident during an upgrade of our CI server. This has been fixed in https://github.com/Clever/saml2/pull/191
