### ISSUE TITLE
G Suite Integration

### ISSUE THREAD

**Issue by ljohnstonbrandcoders** [Clever/saml2#181]
Has anyone has any luck using this with G Suite SAML? I get to the point where I get an empty error and no additional information or errors and I'm pulling my hair out. Looking for any help or suggestions or pointers or whatever.

**Comment by vannicktrinquier** [comment]
@ljohnstonbrandcoders did u find out how to fix this issue ? I have exactly the same problem ?
Thanks

**Comment by ljohnstonbrandcoders** [comment]
Hey @vannicktrinquier. I did get it working, yes. Here's my configuration:

```js
const idp = new saml2.IdentityProvider({
  sso_login_url: "https://accounts.google.com/o/saml2/idp?idpid=<id>",
  sso_logout_url: "https://accounts.google.com/o/saml2/idp?idpid=<id>",
  certificates: [
    fs.readFileSync("idp.pem").toString()
  ],
  allow_unencrypted_assertion: true
});

const sp = new saml2.ServiceProvider({
  entity_id: "https://url",
  assert_endpoint: "https://url/saml/assert",
  private_key: fs.readFileSync("sp.pem").toString(),
  certificate: fs.readFileSync("sp.crt").toString()
});
```

I hope that helps!

**Comment by vannicktrinquier** [comment]
@ljohnstonbrandcoders , yes i make it working. I was using wrong certificate.
Thanks for your help !
