### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by gabegorelick** [Clever/saml2#184]
Has this module been abandoned? The [last commit](https://github.com/Clever/saml2/commit/cc947c29121b183416a79f263572ba9c86a91291) was in January. The last release was in [May 2018](https://github.com/Clever/saml2/commit/5121dd2fb05a894412606f4daa1aa216d959df60). [PRs](https://github.com/Clever/saml2/pull/159) [get](https://github.com/Clever/saml2/pull/143) [no](https://github.com/Clever/saml2/pull/177) [response](https://github.com/Clever/saml2/pull/167). Requests to publish a new version have gone [unanswered](https://github.com/Clever/saml2/issues/176#issuecomment-509696166).

It's totally fine if Clever doesn't want to maintain this anymore. But if that's the case, can some new maintainers be added to the project? Or should the community fork?

**Comment by SJAnderson** [comment]
+1 for community forking.

**Comment by gabegorelick** [comment]
> what's a good alternative than this library

I haven't used it myself, but https://samlify.js.org looks promising.

**Comment by cozmo** [comment]
Hey all! 

First of all, sorry for the radio silence here. It's "back to school" right now, which is Clever's busiest time of the year, and we've all been a little underwater. 

That said - This library is certainly not abandoned, we use it in production to serve millions of logins per day. As such, for Clever's use case, we'd consider this library relatively feature complete. That said we recognize that the potential surface area of SAML is large, and this library currently covers a small part of it. While Clever may not be investing resources in expanding the scope of this library, we want to be good open source citizens and encourage/support ongoing development of features. As such in the coming weeks we'll be 

1. Investing in modernizing the codebase. In practice this will likely mean converting to Typescript, updating/improving the documentation, making sure the CI testing/publishing works, etc. 
2. Merging any outstanding issues/PRs that are in a good state to merge/resolve.
3. Commenting/providing feedback on issues/PRs that are waiting for feedback from Clever
4. Closing issues/PRs that are no longer relevant etc.
5. Making sure we have the processes internally to stay on top of issues/PRs going forward. 

Please let us know if there are additional questions.

**Comment by gabegorelick** [comment]
Thank you @cozmo. That is a satisfying answer to me, so I will close this issue.
