### ISSUE TITLE
obtaining certificate files

### ISSUE THREAD

**Issue by sweetodev** [Clever/saml2#186]
Am I required to buy the certificates from public sites likes `digicerts` for public facing sites? 

With the requirements of using X509Certificate including two subdomains the cost is going around $400+. Just wanted to confirm before I go ahead with the purchase. Please advise.

**Comment by cozmo** [comment]
This library is meant to support your existing SAML setups, but is meant to be flexible to the consumers needs, and as such leaves much of the options (aka how to generate certs) up to the consumer. 

That said, there is no need for the certs to be signed by a trusted certificate authority, and so you should not need to buy any certificates, self signed certs will work just fine. 

Please re-open/comment if you have additional comments/questions.
