### ISSUE TITLE
Not working on Webpack

### ISSUE THREAD

**Issue by ryansmith94** [Clever/saml2#197]
Please can you just upgrade `xml-encryption` to `^1.0.0` so that this works on Webpack? See related issue below.

https://github.com/auth0/node-xml-encryption/issues/55

**Comment by maazmk** [comment]
any news on the fix?

**Comment by mcab** [comment]
As of 2.0.6, we've bumped the version of `xml-encryption` to `^1.2.1`. Does that fix the issue?

**Comment by mcab** [comment]
This dependency has been bumped up since October, and with no reported failures, I'll assume it worked.

Please reopen this issue if this isn't the case.
