### ISSUE TITLE
xmlbuilder dependency doesn't support Node 12 (LTS)

### ISSUE THREAD

**Issue by Hazno** [Clever/saml2#199]
The current version of saml2-js (v2.0.5) is using xmlbuilder ~2.2.0 as a dependency. This version of xmlbuilder doesn't support Node 12, which is currently the LTS version of Node. This results in the following warnings during npm install:

> npm WARN notsup Unsupported engine for xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"12.16.1","npm":"6.13.4"})
> npm WARN notsup Not compatible with your version of node/npm: xmlbuilder@2.2.1

Any chance the xmlbuilder dependency can be updated to support Node 12 (LTS)?

**Comment by ac9** [comment]
xmlbuilder ~2.2.0 also does not support Node 13. xmlbuilder was set to 2.20 due to the following:
https://github.com/Clever/saml2/pull/110
This was about 2 years ago, not sure if xmlbuilder@15.1.1 still has these issues.

**Comment by jnardone** [comment]
Has there been any consideration to update this library?  This is a very useful lib but these ancient dependencies make it very hard to justify in newer code.

**Comment by mcab** [comment]
Yep! Trying to address dependency updates in #212, but will probably need a deeper dive. `xmlbuilder` was rereleased under https://github.com/oozcitak/xmlbuilder2, and I have to validate that migrating to that new version doesn't break things.

**Comment by mcab** [comment]
I've bumped up `xmlbuilder` to `xmlbuilder2`, getting rid of this message:

```
❯ npm i
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN testests@1.0.0 No description
npm WARN testests@1.0.0 No repository field.

added 27 packages from 123 contributors and audited 27 packages in 1.449s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

Feel free to reopen if this is still an issue.
