### ISSUE TITLE
Typescript errors with underscore calls

### ISSUE THREAD

**Issue by aw-pf** [Clever/saml2#203]
I've been using saml2 in my project for a while now, but it's stopped working when I build a new container. I've tried forcing versions of underscore, typescript, and node but I'm having trouble finding a short term workaround until the issue is resolved. The error that is returned is "_ is not a function", this along with the stack trace should shows it's the "_(object).doSomething" that is the issue, the _.doSomething(object) calls all seem to be OK.

This line in the ServiceProvider class constructor:
this.shared_options = _(options).pick("force_authn"...

Could be:
this.shared_options = _.pick(options, "force_authn"...

And in the create_authn_request function this:
context_element = _(context.class_refs).map(function(class_ref) {

Could be more like this (vanilla JS): 
context_element = context.class_refs.map(function(class_ref) {

Or this:
context_element = _.map(context.class_refs, function(class_ref) {

None of my projects are CoffeeScript and I'm under a tight deadline to get a patch tested and into my production environment but this issue is stopping my login from working.

I tried copying the already complied saml2-js/lib-js/saml2.js file directly into my project so I could get it working and whilst I've fixed the underscore issues I still can't get a working SSO session with MS Azure as per how it was working last month. I get some very strange issues:
AADSTS7500517: The element 'RequestedAuthnContext' in XML namespace 'urn:oasis:names:tc:SAML:2.0:protocol' cannot be empty.

So I set it in my config I set:
auth_context: { comparison: "exact", class_refs: ["urn:oasis:names:tc:SAML:2.0:ac:classes:Password"] }

But then I get:
Message: AADSTS7500512: XML element 'RequestedAuthnContext' in XML namespace 'urn:oasis:names:tc:SAML:2.0:protocol' was not expected in the SAML message. Either the element is not an expected part of a SAML message or was in the wrong location in the message. Check the names and ordering of the elements to confirm they conform to the SAML protocol specifications.

I've looked at the code but I'm really not sure how my config object is suddenly wrong / different when I use the directly imported version of the lib.

I'm struggling because I can't remote debug any of the servers that are still working and if I rebuilt them with debug on or lots of console.logs I'd just get the same failures I'm getting with the node module and directly imported versions.

Apologies this is a little vague but I'm so stuck I wanted to reach out!

**Comment by alex-woodall-premierfoods** [comment]
Seems to be an issue with 1.9.2 of Underscore, works OK with 1.9.1. Not tried 1.10.x but needs a PR on package.json in either case

**Comment by mcab** [comment]
`package.json` pulls in `^1.8.0`, which has pulled in `1.12.0` when I install this package in a node project.

Do you still experience this issue?

**Comment by aw-pf** [comment]
I set the parent project to use the specific 1.9.1 version of underscore, that meant that saml2 just used that instead of installing it's own. Not gone back and retried it with a more recent version of underscore / taken out my extra import.

**Comment by mcab** [comment]
Given the outcome, I'll close this issue out.

If you don't believe this is satisfactory, feel free to reopen.
