### ISSUE TITLE
Types for post_assert options are incomplete

### ISSUE THREAD

**Issue by flipace** [Clever/saml2#205]
I just noticed that the types for `sp.post_assert` options are incomplete. Typings only include `request_body` and `allow_unencrypted_assertion`.

`require_session_index`, `notbefore_skew`, and `audience` should be added as well (they are noted in the docs).

**Comment by mcab** [comment]
It seems that https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49787 has addressed this.

Please reopen this issue if this isn't the case.
