### ISSUE TITLE
Saml2 - Azure AD using 

### ISSUE THREAD

**Issue by shakthifuture** [Clever/saml2#208]
Is it possible to do SAML authentication in Azure AD using this library in angular application?

**Comment by mcab** [comment]
I'll defer to https://github.com/Clever/saml2/issues/195 here.

Running this library as part of an Angular application would mean running this library client-side, which has the potential to leak private keys. The intent is to have this run server-side on your application to perform authentication / authorization, which the Angular application then deals with the results of those calls.
