### ISSUE TITLE
The docs don't seem to tell us how to specify the passphrase for the "private_key" pem file. 

### ISSUE THREAD

**Issue by PaulSender** [Clever/saml2#221]
I need to specify a passphrase for my key.pem file in order for the service provider to send a signed request. When doing so, I receive 
var ret = this._handle.sign(toBuf(key), passphrase, rsaPadding,
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

which from my experience just means you need to specify that passphrase but the docs don't tell us how to do that with this particular package. Is this possible or should I use passport-saml?

**Comment by mcab** [comment]
Specifying a password to use with the `private_key` is not supported by this library.

However, the underlying dependency (xml-crypto) hints that this error is different: https://github.com/yaronn/xml-crypto/issues/123.

Can you attempt the issue with and without a passphrase on the `private_key`?

**Comment by PaulSender** [comment]
I was able to bypass this issue by creating a pem file without a passphrase.

**Comment by mcab** [comment]
Given the proposed solution, I'll close this issue out.

If you don't believe this is satisfactory, feel free to reopen.
