### ISSUE TITLE
How to use saml2 as an idp

### ISSUE THREAD

**Issue by blacktrue** [Clever/saml2#239]
Hi,

I can't find examples on how to use this library as an idp, that is, the sp will be connected to my implementation.

Any example?

**Comment by hamjoe** [comment]
It seems this library was not designed for that purpose, please see [this issue](https://github.com/Clever/saml2/issues/130).

**Comment by mcab** [comment]
Addressed in https://github.com/Clever/saml2/commit/6e718ec62913633f795131e37f639ccac37a3c12
