### ISSUE TITLE
 Misinterpretation of malicious XML input

### ISSUE THREAD

**Issue by apostolovm** [Clever/saml2#240]
Hi, will you please update your dependencies. To be more specific xmldom to version 0.7.0 or higher.

**Comment by dsuarezlogans** [comment]
can I open a PR for this?

**Comment by apostolovm** [comment]
Sure

**Comment by dbauszus-glx** [comment]
Should be resolved once this is merged. [#245](https://github.com/Clever/saml2/pull/245)

There is a [xmldom 0.8.0 release](https://github.com/xmldom/xmldom/releases/tag/0.8.0). Might be wirth using the latest version now.

**Comment by mcab** [comment]
Addressed in https://github.com/Clever/saml2/pull/261.
