### ISSUE TITLE
Node-forge vulnerabilities

### ISSUE THREAD

**Issue by pawelzygmuntowski** [Clever/saml2#248]
The node-forge version used in node-xml-encryption that saml2 uses has some vulnerabilities.

https://deps.dev/advisory/GHSA/GHSA-5rrq-pxf6-6jx5 - Prototype Pollution in node-forge debug API.
and also
https://deps.dev/advisory/GHSA/GHSA-gf8q-jrpm-jvxq - URL parsing in node-forge could lead to undesired behavior.

This was fixed in the newest version of node-xml-encryption:
https://github.com/auth0/node-xml-encryption/issues/94

So upgrading node-xml-encryption to the latest release should fix this.

 Can we expect this to be fixed any time soon?

**Comment by slowtick** [comment]
Would be interested in fix for this. The newer version of xml-encryption (2.0.0) seems to be api compatible. With nodejs 16.x added a [dependency override](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) in my package.json as in below and it worked with current release of saml2-js.

```
"overrides": {
    "saml2-js": {
      "xmldom": "^0.6.0",
      "xml-encryption": "^2.0.0"
    }
  }
```

**Comment by darioackermann** [comment]
I am mainting a fork of this repo with all dependency updates applied. Feel free to use it in any case.

**Comment by mcab** [comment]
Addressed in https://github.com/Clever/saml2/pull/261.
