### ISSUE TITLE
This repo is unmaintained - security fork

### ISSUE THREAD

**Issue by darioackermann** [Clever/saml2#257]
Hi all.

Since we require this library on our end, I've created a fork where we try to apply upcoming security fixes in order to maintain vulnearbilities low. You can install the fork by `npm install @darioackermann/saml2-js`

https://www.npmjs.com/package/@darioackermann/saml2-js

Cheers

**Comment by seanmacisaac** [comment]
Thank you @darioackermann

Seems particular important for a authentication library :)

**Comment by darioackermann** [comment]
Closing this as repo is maintained again. Fork is deprecated as of last week.
