### ISSUE TITLE
Question: can this library support SAML assertion/response generation?

### ISSUE THREAD

**Issue by Sue2015** [Clever/saml2#258]
can this library support the functionality of mimicking IDP to generate SAML response? I only see the support of parsing and validating SAML response from IDP.

**Comment by darioackermann** [comment]
No. This library was not created for this
Related: #239 #130

**Comment by mcab** [comment]
Closed via f3692955f616e4b85e015d7b41a08c07e58d2614.

Please comment if the wording can be improved.
