### ISSUE TITLE
are there any release notes? what happened between 3.0.1->4.0.1?

### ISSUE THREAD

**Issue by donhcd** [Clever/saml2#266]
I'd like to upgrade my version but I'm a bit nervous - why was the major version bumped?

**Comment by mcab** [comment]
The explicit version bumps houses the messages. I'll try to be clearer on the merge.

3.0.1: https://github.com/Clever/saml2/commit/fca725bc329487d2ae6cf0fdff93b3bae23e3323
> Bumping up xmlbuilder to xmlbuilder2 revealed some differences in XML building.
>
> This fixes `create_metadata()` to output correctly given these new changes.

3.1.0: https://github.com/Clever/saml2/commit/c197310c1f3f8ee6d6c889b60b51e580f3239214
> - Closes https://github.com/Clever/saml2/pull/183. Addresses some issues with using the example in strict mode.
> - Closes https://github.com/Clever/saml2/pull/231. Replaces Buffer() with Buffer.from().
> - Closes https://github.com/Clever/saml2/pull/233. Uses underscore in a manner more compatible with TypeScript.
> - Closes https://github.com/Clever/saml2/pull/238. Replaces body-parser with urlencoded() for express >=4.
> - Adds maintenance notice.

4.0.0: https://github.com/Clever/saml2/commit/cfb5ce43023bcabbc10ed6ff26ae8c70a24a01b4
> Updates some dependencies.
>
> Closes [...].

From https://github.com/Clever/saml2/pull/261#issuecomment-1302426392:
> - xml-encryption was bumped up to [^2.0.0](https://github.com/auth0/node-xml-encryption/releases/tag/v2.0.0), which drops support for Node 8, and uses native crypto functions. Any user still on Node 8 will be unable to use 4.x and onwards.
> - @xmldom/xmldom was bumped up to ^0.8.3. This has a security fix for [prototype pollution](https://github.com/xmldom/xmldom/releases/tag/0.8.3) and other [cases](https://github.com/xmldom/xmldom/releases/tag/0.7.0), but more critically, changes how [normalization and serialization](https://github.com/xmldom/xmldom/releases/tag/0.8.0) of XML documents occur. This can potentially affect the parsing of XML documents, but shouldn't affect the majority of cases.
> - xml-crypto was bumped up to [^3.0.0](https://github.com/yaronn/xml-crypto/releases/tag/v3.0.0), which uses @xmldom/xmldom's 0.8.3. If you don't find issues with xmldom parsing, you should be fine.

4.0.1: https://github.com/Clever/saml2/commit/fe30eee749438b52b254f2f4eaf74d4781538c76
> Addresses https://github.com/advisories/GHSA-crh6-fp67-6883 [1] by updating @xmldom/xmldom explicitly,
and other dependencies that use such.
> 
> [1] [GHSA-crh6-fp67-6883](https://github.com/xmldom/xmldom/security/advisories/GHSA-crh6-fp67-6883)

**Comment by mcab** [comment]
In short, a lot of dependencies around normalization around XML parsing were updated, especially for critical dependencies that handle decryption and parsing. Major bumps might be overkill, but it's possible people are still using this on Node <10, and wanted to not break things for those users.

**Comment by donhcd** [comment]
Thanks a ton for the summary @mcab! Good to know where they are now :)
