### ISSUE TITLE
Question: Can this be used in Restify?

### ISSUE THREAD

**Issue by clarkio** [Clever/saml2#36]
I notice this references use in Express, but I'm wondering if this can be used within a Restify server instead. Would this be possible or is it built for use in just Express?

Thanks.

**Comment by jefff** [comment]
I'm not familiar with Restify but there should be nothing about the library that is Express specific.

**Comment by clarkio** [comment]
@jefff thanks for the quick response.

Restify is similar to Express, but I believe their main difference, in regard to compatibility of modules written for them, is in the handling of responses (e.g. `res.status(200).send({});` vs `res.send(200, {});`)

Here are some links to Restify in case you're interested:
1. http://mcavage.me/node-restify/
2. https://github.com/restify/node-restify

**Comment by jefff** [comment]
Interesting, thanks for the links.

I don't see anything here that would cause any issues. The library does not issue it's own redirects or responses, it simply returns them and leaves that to the consumer. You may need some form of body parsing middleware for the assertion endpoint (or you could manually parse them before passing them in). I imagine you'd only need some minor changes to the example code included in the README to get things working.
