### ISSUE TITLE
Give Values for Options

### ISSUE THREAD

**Issue by britztopher** [Clever/saml2#37]
I am thinking of using saml2, however, there is one issue.  How can we add values to the xml?  For example:

``` xml
 <saml2:Subject>
    <saml2:NameIDFormat="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">Customer_Id</saml2:NameID>
    <saml2:SubjectConfirmationMethod="urn:oasis:names:tc:SAML:2.0:cm:bearer"/>
  </saml2:Subject>
```

As one can see the `NameIDFormat` attribute within subject contains a `Customer_Id` within that.  I think adding a way to add values and attributes would be very useful

**Comment by jefff** [comment]
I'm not sure if I understand the question. The values specified as the NameID come from the Identity Provider and would be read by this library rather than set by it. It should be able to read arbitrary NameID values the IDP sends.

Can you clarify what you're trying to do?

**Comment by mohit** [comment]
Closed due to no response.
