### ISSUE TITLE
Sign the metadata

### ISSUE THREAD

**Issue by peterwillis** [Clever/saml2#40]
According to the specification and wikipedia the service provider metadata should be signed (https://en.wikipedia.org/wiki/SAML_2.0#Service_Provider_Metadata)

Could you change it so that if sign_get_request is enabled on the service provider, create_metadata signs the metadata? Would you accept a pull request for this?

**Comment by jefff** [comment]
In practice, I've never seen a system that required (or even requested) a metadata be signed. Usually it's required to be served over https for authenticity.

At some point it may be added to this library but it currently isn't planned. If you were interested in adding it, I would accept a PR.

**Comment by peterwillis** [comment]
ok thank you
