### ISSUE TITLE
Shibboleth support?

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [Clever/saml2#43]
Hi :)

I've successfully used saml2 to integrate with ADFS as well as Okta. ADFS automatically configures itself when given the metadata produced by saml2, which is superb :)

Next up I'd like to support Shibboleth as well, but I'm running into problems when trying to test against it using the metadata [upload form](https://www.testshib.org/register.html) at TestShib — I simply get the error `The file you are attempting to upload is not valid metadata. Please correct any errors and try again.`.

Not a lot of info there, so I thought I'd try testing the XML against the [XSD](http://docs.oasis-open.org/security/saml/v2.0/saml-schema-metadata-2.0.xsd). This fails on the XSD end, and looks like it's due to some imports that fail...

I'll continue digging, but thought I'd raise the issue here as well, in case this is a known limitation or someone else has encountered this issue as well.

Cheers, and thanks for a great library!

**Comment by DanielSmedegaardBuus** [comment]
Turned out to be Shibboleth being extremely strict about the ordering of elements in the metadata. Made the changed an created a [pull request](https://github.com/Clever/saml2/pull/44)

**Comment by azylman** [comment]
Resolved by #44
