### ISSUE TITLE
ignore_signature xml assertion problem

### ISSUE THREAD

**Issue by melkior** [Clever/saml2#55]
Hi,

been trying to use ignore_signature option like this:

    var options = {request_body: body, ignore_signature: true};
    sp.post_assert(idp, options, function(err, saml_response) { ... }

saml2-js returns this error:

Expected 1 Assertion; found 0

Problem seems to be in lib-js/saml2.js - parse_authn_response()

    if (ignore_signature) {
        return cb_wf(null, (new xmldom.DOMParser()).parseFromString(result));
    }

After little big of juggling this works:

    if (ignore_signature) {
        return cb_wf(null, saml_response);
    }

Looks like result is already xml 'Assertion', but it will try to get 'Assertion' again in get_name_id which gives error.

So, can you please tell me if I'm doing something wrong, because i can't test much on current infrastructure.

Thank you.

**Comment by jefff** [comment]
I confess this is a rarely used option so it's very possible there's a regression here. That being said, I can't seem to reproduce this issue on any of the test files I have. Can you post a request body that causes this issue? If you'd rather not post it publicly, you could also email it to me at jeff.nelson@clever.com

**Comment by melkior** [comment]
Ok thanks. Omw
