### ISSUE TITLE
is "certificate" really required?

### ISSUE THREAD

**Issue by SamDecrock** [Clever/saml2#76]
Hi,

In the SP, is "certificate" really required? Because I don't seem to need it to make a successful SAML authentication.

Cheers,
Sam

**Comment by Guuz** [comment]
Any chance of a reply to this issue? I'm curious as well.

**Comment by guerilla7** [comment]
@SamDecrock and @Guuz 

Yes, the SP needs to obtain a public certificate from the IDP to validate the signature. The certificate is stored on the SP side and used whenever a SAML response arrives.

**Comment by indykid** [comment]
Hi, could you please confirm if the IDP options refer to the same certificate(s)?

Thank you,
J

**Comment by guerilla7** [comment]
@indykid 

Yo!  A certificate is required under the sp_options like so:

`// Create service provider
var sp_options = {
  entity_id: "https://sp.example.com/metadata.xml",
  private_key: fs.readFileSync("key-file.pem").toString(),
  certificate: fs.readFileSync("cert-file.crt").toString(),
  assert_endpoint: "https://sp.example.com/assert"
};`

Same thing with the idp_options, like so:

`// Create identity provider
var idp_options = {
  sso_login_url: "https://idp.example.com/login",
  sso_logout_url: "https://idp.example.com/logout",
  certificates: [fs.readFileSync("cert-file1.crt").toString(), fs.readFileSync("cert-file2.crt").toString()]
};`

The difference between sp_options and idp_options is that under idp_options you can define just one certificate or an array of certificates in PEM format strings like so:

`certificates: [fs.readFileSync("cert-file1.crt").toString(), fs.readFileSync("cert-file2.crt").toString()]`

Let me know if it sounds clear?

Thanks!

**Comment by thomassuckow** [comment]
The certificate and private key in the SP is your applications cert. That proves to the Identity Provider (Probably active directory) that your application is authorized. This prevents some random person from making a clone of your application and tricking users into authenticating with it.

The certificate(s) in the IdP are of the Identity Provider. They are used when the IdP signs the response to your application. This prevents someone from pretending to be the IdP and tricking your application into thinking they are someone they are not. These certificates are probably published somewhere, such as https://accounts.accesscontrol.windows.net/common/FederationMetadata/2007-06/FederationMetadata.xml specifically in IDPSSODescriptor

**Comment by cozmo** [comment]
Last comment on this issue was in 2017 and it seems to be answered (thanks all for jumping in). As such I'm going to close this issue. 

If there are still questions around this please feel free to comment/re-open.
