### ISSUE TITLE
SAML Consumer?

### ISSUE THREAD

**Issue by Gobliins** [Clever/saml2#88]
Just want to know if i understand this library correct.

I have an IDP (Azure AD) and want to do a SAML login from a pure client sided (no express) javascript in Browser app.
Something like doing the SAML redirect to the login page and grabbing (opt. validating) the SAML response form the IDP.

Is this possible with this library?

**Comment by sibelius** [comment]
@Gobliins did you figure it out?

**Comment by cozmo** [comment]
Closing this issue as no response to this issue for a year+, if anyone still has questions feel free to comment/re-open.
