### ISSUE TITLE
security scan failing

### ISSUE THREAD

**Issue by ghafran** [Clever/saml2#90]
After scanning saml2-js module.
```
npm install saml2-js --save
npm install nsp --global
nsp check
```
Getting this issue:

![screen shot 2017-01-03 at 10 46 43 am](https://cloud.githubusercontent.com/assets/769045/21613137/f29686bc-d1a1-11e6-857d-7cbc29b389f0.png)

Looks like its using outdated modules....

**Comment by guerilla7** [comment]
@ghafran It's the "debug" dependency using an outdate version of "ms" library described in node security advisory 46:
https://github.com/visionmedia/debug/blob/master/package.json

The latest version of "debug" in npm is 2.6.1 
https://www.npmjs.com/package/debug

I updated mine, did an NPM install and re-ran node security scanner and all dependencies pass that vulnerability checks:
<img width="351" alt="screen shot 2017-02-27 at 3 18 32 pm" src="https://cloud.githubusercontent.com/assets/2307524/23384538/42d1f4ac-fd00-11e6-8091-cb0f3820df99.png">
