### ISSUE TITLE
Working with multiple idp's

### ISSUE THREAD

**Issue by adibPlaybuzz** [Clever/saml2#91]
Hi,
I would like to work with multiple idp's (configuration is based on user's email).
However, since the service is state-less - on the /assert enpoint of my service i need to call post_assert and pass the idp - is there some key (passing in the session) that can help me understand which idp should i call?

**Comment by mattridley** [comment]
On my project I simply include the idp id in the url and use that to create a new IDP and SP instance for each request. For example:

/saml/:idp <- Metadata
/saml/:idp/login <- Entry point for app to redirect to which then generates the SAMLRequest and redirects
/saml/:idp/assert <- For processing the IdP response

I then simply look up the IdP details from the database and construct the SP and IdP objects.

**Comment by adibPlaybuzz** [comment]
@mattridley Thanks, very helpful - i used the relay_state.

Do you parse each idp attributes (i have one idp with 'Email' attribute and one with 'email' attribute)?

**Comment by mattridley** [comment]
No. If a customer only wants to grant access to existing accounts we just get them to send us the email address as the Name ID and log them in from that.

If they wish to auto-create new accounts then they also need to send the name and job title so we can set that up for them.

We have no use for the other fields and so even if they are sent we don't parse them.

**Comment by mohit** [comment]
Thanks @mattridley for the response! Going to close this issue.
