### ISSUE TITLE
Signed data did not contain a SAML Assertion! fails simple response

### ISSUE THREAD

**Issue by bensimian** [Clever/saml2#93]
Testing with the example with Onelogin SAML Encrypted test connector, but fails with 'Signed data did not contain a SAML Assertion!'. I only needed to get the user email address to validate our application rule against. Quite new to SSO and managed to change 

`signed_dom = (new xmldom.DOMParser()).parseFromString(sn);`

  to          

` signed_dom = (new xmldom.DOMParser()).parseFromString(result); `

which yields the expected behaviour after debugging as the result contained the assertion and email address.  Am i missing a setting/param to make it work as intended with  

`signed_dom = (new xmldom.DOMParser()).parseFromString(sn);`

great work putting this together!

**Comment by jonime** [comment]
I have the same problem. `parse_authn_response` function uses undecrypted response when checking for assertions and it fails to find one, because the assertion is inside the crypted content.

I managed to skip this bug using `ignore_signature` option before it has been fixed.

**Comment by bensimian** [comment]
confirmed this works by setting ignore signature. Thanks @jonime
