### ISSUE TITLE
NameIDFormat not specified in metadata

### ISSUE THREAD

**Issue by amv** [Clever/saml2#94]
When exporting SP metadata, md:NameIDFormat is not present in the xml even if it is defined for the ServiceProvider options.

My current understanding is that this should be present inside the md:SPSSODescriptor element.

**Comment by amv** [comment]
I was hoping adding this would allow ADFS IdP to work without additional configuration, but after testing it seems I was wrong. Thus I am not sure if this is critical, or even beneficial in any situation. If nobody has additional information about this, I'm ok with closing this ticket.

**Comment by jefff** [comment]
I'm not 100% sure, but I believe for ADFS you need a special rule to send NameID. You should be able to pick 'Name ID' as the outgoing claim type on most claim rule templates (Like, 'Send LDAP Attributes as Claims')

**Comment by cozmo** [comment]
Closing this issue as no response to this issue for a year+, if anyone still has questions feel free to comment/re-open.
