### ISSUE TITLE
Attempting to decrypt an assertion with an invalid certificate throws an unhandled exception

### ISSUE THREAD

**Issue by tomlagier** [Clever/saml2#97]
Issue happens because check_saml_signature can throw an exception if the certificate is invalid. Issue stems from xml-crypto throwing when invalid XML is provided, but the most logical place to catch the error is at [lib/saml2.coffe line 444](https://github.com/Clever/saml2/blob/master/lib/saml2.coffee#L444). PR to fix incoming.

**Comment by cozmo** [comment]
Based on the comment in #98 it seems this has been resolved. Closing, but feel free to re-open if the issue still exists.
